# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1ad42c627cb448d2d58c35d6d0fdf1908d65f5c3eec291d735a888b7b130653c8493ecc399998b7f28df03ae1acbce661ab52249c5709e6e7d828c33174c032

test:
  secret_key_base: 74663208822c79d894e9de065302a6c5846738af645585bbd4497fe78c25dc474ec4a197230483661c8043129abeaf52f4730f5f18b206313edb19372dd32806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
